language: c++
rvm:
  - g++
os: linux
script: travis/cmake.sh
matrix:
  include:
    - os: linux
      dist: bionic
      sudo: true
      compiler: gcc
      addons:
        apt:
          packages:
            - g++
            - libgtest-dev
            - cmake